### ISSUE TITLE
FEE: Yak Shaving Checklist

### ISSUE THREAD

**Issue by al-the-x** [TheIronYard--Orlando/TIY-Catalog#6]
- [ ] Add your names to the `authors` and `contributors` keys in `package.json` and `bower.json`
- [ ] Add and save our dependencies with `bower` and `npm`
- [ ] Clean up `src/`
  - [ ] Remove stuff we don't need from H5BP: jQuery, `main.css`, `normalize.css`, etc
  - [ ] Make `scss/` folder for Sass files
- [ ] Read assignment for more...
